image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/drifblim
sources:
    - https://git.sr.ht/~rabbits/uxn11
    - https://git.sr.ht/~rabbits/drifblim
tasks:
    - prepare: |
        cd uxn11
        cc src/uxnasm.c -o ../uxnasm
    - assemble: |
        cd drifblim
        ../uxnasm src/drifblim.tal ../drifblim.rom
    - upload: |
        tar -czf out.tar.gz drifblim.rom
        acurl() {
            set +x
            curl -H "Authorization: Bearer ${OAUTH2_TOKEN}" "${@}"
            set -x
        }
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz
